/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DocumentationEntrySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'generatedContent',
    'id',
    'projectId',
    'sourceRef',
    'sourceType',
    'status',
    'updatedAt',
  ] as const
  $columns = DocumentationEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare generatedContent: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
  @column()
  declare sourceRef: string
  @column()
  declare sourceType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LlmProviderConfigSchema extends BaseModel {
  static $columns = [
    'baseUrl',
    'createdAt',
    'encryptedApiKey',
    'id',
    'isActive',
    'model',
    'provider',
    'updatedAt',
  ] as const
  $columns = LlmProviderConfigSchema.$columns
  @column()
  declare baseUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare encryptedApiKey: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare model: string | null
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'gitProvider',
    'id',
    'llmProviderConfigId',
    'name',
    'repositoryUrl',
    'updatedAt',
    'webhookSecret',
  ] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gitProvider: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare llmProviderConfigId: string | null
  @column()
  declare name: string
  @column()
  declare repositoryUrl: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare webhookSecret: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
